version: "3.8"

x-env: &default_env
  OPENAI_API_KEY: ${OPENAI_API_KEY:-}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
  HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN:-}
  CHROMA_DB_PATH: /app/chroma_db
  DATA_PATH: /app/data
  SESSIONS_PATH: /app/sessions

services:
  app:
    build: .
    image: agentic-ai-research:latest
    container_name: agentic-ai-research
    command: web
    env_file: .env
    environment: *default_env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [ai-network]

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks: [ai-network]

networks:
  ai-network:
    driver: bridge

volumes:
  redis_data: